# -*- coding: utf-8 -*-
from resources.jsonWorker import read, write
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
FILE = 'resources/timetable.json'
timetableDATA = read(FILE)
LESSONSSTYLESHEET = """
            background-color:rgb(255, 166, 103);
            border: 0;
            margin: 0;
            border-radius: 3;
            color: black;
            padding: 3;
            border-style: solid;
            border-width: 1.5px;
            border-color: rgb(255, 133, 62);
            font-size: 13px;
        """
DAYSLINESSTYLESHEET = """
            background-color: rgb(255, 133, 62);
            border: 0;
            margin: 0;
            border-radius: 5;
            color: white;
        """


class Ui_editTimetable(object):
    def save(self):
        editedTimetableData = dict()
        for x in range(1, 7):
            lessons = dict()
            for y in range(1, 7):
                lessons[f"lesson{y}"] = getattr(self, f"D{x}lesson{y}").text()
            editedTimetableData[f"D{x}"] = lessons.copy()
            del lessons
        write(FILE, editedTimetableData)
        

    def setupUi(self, editTimetable):
        editTimetable.setObjectName("editTimetable")
        editTimetable.resize(915, 499)
        editTimetable.setMinimumSize(QtCore.QSize(640, 480))
        editTimetable.setWindowIcon(QtGui.QIcon('icon.ico'))
        font = QtGui.QFont()
        font.setPointSize(12)
        editTimetable.setFont(font)
        editTimetable.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0             rgba(255, 117, 83, 255), stop:1 rgba(255, 255, 255, 255))")
        self.verticalLayout = QtWidgets.QVBoxLayout(editTimetable)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QLabel(editTimetable)
        self.header.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.header.setFont(font)
        self.header.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.header.setStyleSheet("""
            color: rgb(0, 0, 0);
            background-color: none;
        """)
        self.header.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.header.setObjectName("header")
        self.verticalLayout.addWidget(self.header)
        self.daysLine1Names = QtWidgets.QHBoxLayout()
        self.daysLine1Names.setObjectName("daysLine1Names")
        self.day1Line1Name = QtWidgets.QLabel(editTimetable)
        self.day1Line1Name.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.day1Line1Name.setFont(font)
        self.day1Line1Name.setStyleSheet(DAYSLINESSTYLESHEET)
        self.day1Line1Name.setAlignment(QtCore.Qt.AlignCenter)
        self.day1Line1Name.setObjectName("day1Line1Name")
        self.daysLine1Names.addWidget(self.day1Line1Name)
        self.day3Line1Name = QtWidgets.QLabel(editTimetable)
        self.day3Line1Name.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.day3Line1Name.setFont(font)
        self.day3Line1Name.setStyleSheet(DAYSLINESSTYLESHEET)
        self.day3Line1Name.setAlignment(QtCore.Qt.AlignCenter)
        self.day3Line1Name.setObjectName("day3Line1Name")
        self.daysLine1Names.addWidget(self.day3Line1Name)
        self.day2Line1Name = QtWidgets.QLabel(editTimetable)
        self.day2Line1Name.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.day2Line1Name.setFont(font)
        self.day2Line1Name.setStyleSheet(DAYSLINESSTYLESHEET)
        self.day2Line1Name.setAlignment(QtCore.Qt.AlignCenter)
        self.day2Line1Name.setObjectName("day2Line1Name")
        self.daysLine1Names.addWidget(self.day2Line1Name)
        self.verticalLayout.addLayout(self.daysLine1Names)
        self.daysLine1 = QtWidgets.QHBoxLayout()
        self.daysLine1.setObjectName("daysLine1")
        self.day1Lessons = QtWidgets.QVBoxLayout()
        self.day1Lessons.setObjectName("day1Lessons")
        self.D1lesson1 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D1lesson1.sizePolicy().hasHeightForWidth())
        self.D1lesson1.setSizePolicy(sizePolicy)
        self.D1lesson1.setStyleSheet(LESSONSSTYLESHEET)
        self.D1lesson1.setObjectName("D1lesson1")
        self.day1Lessons.addWidget(self.D1lesson1)
        self.D1lesson2 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D1lesson2.sizePolicy().hasHeightForWidth())
        self.D1lesson2.setSizePolicy(sizePolicy)
        self.D1lesson2.setStyleSheet(LESSONSSTYLESHEET)
        self.D1lesson2.setObjectName("D1lesson2")
        self.day1Lessons.addWidget(self.D1lesson2)
        self.D1lesson3 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D1lesson3.sizePolicy().hasHeightForWidth())
        self.D1lesson3.setSizePolicy(sizePolicy)
        self.D1lesson3.setStyleSheet(LESSONSSTYLESHEET)
        self.D1lesson3.setObjectName("D1lesson3")
        self.day1Lessons.addWidget(self.D1lesson3)
        self.D1lesson4 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D1lesson4.sizePolicy().hasHeightForWidth())
        self.D1lesson4.setSizePolicy(sizePolicy)
        self.D1lesson4.setStyleSheet(LESSONSSTYLESHEET)
        self.D1lesson4.setObjectName("D1lesson4")
        self.day1Lessons.addWidget(self.D1lesson4)
        self.D1lesson5 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D1lesson5.sizePolicy().hasHeightForWidth())
        self.D1lesson5.setSizePolicy(sizePolicy)
        self.D1lesson5.setStyleSheet(LESSONSSTYLESHEET)
        self.D1lesson5.setObjectName("D1lesson5")
        self.day1Lessons.addWidget(self.D1lesson5)
        self.D1lesson6 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D1lesson6.sizePolicy().hasHeightForWidth())
        self.D1lesson6.setSizePolicy(sizePolicy)
        self.D1lesson6.setStyleSheet(LESSONSSTYLESHEET)
        self.D1lesson6.setObjectName("D1lesson6")
        self.day1Lessons.addWidget(self.D1lesson6)
        self.daysLine1.addLayout(self.day1Lessons)
        self.day2Lessons = QtWidgets.QVBoxLayout()
        self.day2Lessons.setObjectName("day2Lessons")
        self.D2lesson1 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D2lesson1.sizePolicy().hasHeightForWidth())
        self.D2lesson1.setSizePolicy(sizePolicy)
        self.D2lesson1.setStyleSheet(LESSONSSTYLESHEET)
        self.D2lesson1.setObjectName("D2lesson1")
        self.day2Lessons.addWidget(self.D2lesson1)
        self.D2lesson2 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D2lesson2.sizePolicy().hasHeightForWidth())
        self.D2lesson2.setSizePolicy(sizePolicy)
        self.D2lesson2.setStyleSheet(LESSONSSTYLESHEET)
        self.D2lesson2.setObjectName("D2lesson2")
        self.day2Lessons.addWidget(self.D2lesson2)
        self.D2lesson3 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D2lesson3.sizePolicy().hasHeightForWidth())
        self.D2lesson3.setSizePolicy(sizePolicy)
        self.D2lesson3.setStyleSheet(LESSONSSTYLESHEET)
        self.D2lesson3.setObjectName("D2lesson3")
        self.day2Lessons.addWidget(self.D2lesson3)
        self.D2lesson4 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D2lesson4.sizePolicy().hasHeightForWidth())
        self.D2lesson4.setSizePolicy(sizePolicy)
        self.D2lesson4.setStyleSheet(LESSONSSTYLESHEET)
        self.D2lesson4.setObjectName("D2lesson4")
        self.day2Lessons.addWidget(self.D2lesson4)
        self.D2lesson5 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D2lesson5.sizePolicy().hasHeightForWidth())
        self.D2lesson5.setSizePolicy(sizePolicy)
        self.D2lesson5.setStyleSheet(LESSONSSTYLESHEET)
        self.D2lesson5.setObjectName("D2lesson5")
        self.day2Lessons.addWidget(self.D2lesson5)
        self.D2lesson6 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D2lesson6.sizePolicy().hasHeightForWidth())
        self.D2lesson6.setSizePolicy(sizePolicy)
        self.D2lesson6.setStyleSheet(LESSONSSTYLESHEET)
        self.D2lesson6.setObjectName("D2lesson6")
        self.day2Lessons.addWidget(self.D2lesson6)
        self.daysLine1.addLayout(self.day2Lessons)
        self.day3Lessons = QtWidgets.QVBoxLayout()
        self.day3Lessons.setObjectName("day3Lessons")
        self.D3lesson1 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D3lesson1.sizePolicy().hasHeightForWidth())
        self.D3lesson1.setSizePolicy(sizePolicy)
        self.D3lesson1.setStyleSheet(LESSONSSTYLESHEET)
        self.D3lesson1.setObjectName("D3lesson1")
        self.day3Lessons.addWidget(self.D3lesson1)
        self.D3lesson2 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D3lesson2.sizePolicy().hasHeightForWidth())
        self.D3lesson2.setSizePolicy(sizePolicy)
        self.D3lesson2.setStyleSheet(LESSONSSTYLESHEET)
        self.D3lesson2.setObjectName("D3lesson2")
        self.day3Lessons.addWidget(self.D3lesson2)
        self.D3lesson3 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D3lesson3.sizePolicy().hasHeightForWidth())
        self.D3lesson3.setSizePolicy(sizePolicy)
        self.D3lesson3.setStyleSheet(LESSONSSTYLESHEET)
        self.D3lesson3.setObjectName("D3lesson3")
        self.day3Lessons.addWidget(self.D3lesson3)
        self.D3lesson4 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D3lesson4.sizePolicy().hasHeightForWidth())
        self.D3lesson4.setSizePolicy(sizePolicy)
        self.D3lesson4.setStyleSheet(LESSONSSTYLESHEET)
        self.D3lesson4.setObjectName("D3lesson4")
        self.day3Lessons.addWidget(self.D3lesson4)
        self.D3lesson5 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D3lesson5.sizePolicy().hasHeightForWidth())
        self.D3lesson5.setSizePolicy(sizePolicy)
        self.D3lesson5.setStyleSheet(LESSONSSTYLESHEET)
        self.D3lesson5.setObjectName("D3lesson5")
        self.day3Lessons.addWidget(self.D3lesson5)
        self.D3lesson6 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D3lesson6.sizePolicy().hasHeightForWidth())
        self.D3lesson6.setSizePolicy(sizePolicy)
        self.D3lesson6.setStyleSheet(LESSONSSTYLESHEET)
        self.D3lesson6.setObjectName("D3lesson6")
        self.day3Lessons.addWidget(self.D3lesson6)
        self.daysLine1.addLayout(self.day3Lessons)
        self.verticalLayout.addLayout(self.daysLine1)
        self.daysLine2Names = QtWidgets.QHBoxLayout()
        self.daysLine2Names.setObjectName("daysLine2Names")
        self.day5Line2Name = QtWidgets.QLabel(editTimetable)
        self.day5Line2Name.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.day5Line2Name.setFont(font)
        self.day5Line2Name.setStyleSheet(DAYSLINESSTYLESHEET)
        self.day5Line2Name.setAlignment(QtCore.Qt.AlignCenter)
        self.day5Line2Name.setObjectName("day5Line2Name")
        self.daysLine2Names.addWidget(self.day5Line2Name)
        self.day6Line2Name = QtWidgets.QLabel(editTimetable)
        self.day6Line2Name.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.day6Line2Name.setFont(font)
        self.day6Line2Name.setStyleSheet(DAYSLINESSTYLESHEET)
        self.day6Line2Name.setAlignment(QtCore.Qt.AlignCenter)
        self.day6Line2Name.setObjectName("day6Line2Name")
        self.daysLine2Names.addWidget(self.day6Line2Name)
        self.day4Line2Name = QtWidgets.QLabel(editTimetable)
        self.day4Line2Name.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.day4Line2Name.setFont(font)
        self.day4Line2Name.setStyleSheet(DAYSLINESSTYLESHEET)
        self.day4Line2Name.setAlignment(QtCore.Qt.AlignCenter)
        self.day4Line2Name.setObjectName("day4Line2Name")
        self.daysLine2Names.addWidget(self.day4Line2Name)
        self.verticalLayout.addLayout(self.daysLine2Names)
        self.daysLine2 = QtWidgets.QHBoxLayout()
        self.daysLine2.setObjectName("daysLine2")
        self.day4Lessons = QtWidgets.QVBoxLayout()
        self.day4Lessons.setObjectName("day4Lessons")
        self.D4lesson1 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D4lesson1.sizePolicy().hasHeightForWidth())
        self.D4lesson1.setSizePolicy(sizePolicy)
        self.D4lesson1.setStyleSheet(LESSONSSTYLESHEET)
        self.D4lesson1.setObjectName("D4lesson1")
        self.day4Lessons.addWidget(self.D4lesson1)
        self.D4lesson2 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D4lesson2.sizePolicy().hasHeightForWidth())
        self.D4lesson2.setSizePolicy(sizePolicy)
        self.D4lesson2.setStyleSheet(LESSONSSTYLESHEET)
        self.D4lesson2.setObjectName("D4lesson2")
        self.day4Lessons.addWidget(self.D4lesson2)
        self.D4lesson3 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D4lesson3.sizePolicy().hasHeightForWidth())
        self.D4lesson3.setSizePolicy(sizePolicy)
        self.D4lesson3.setStyleSheet(LESSONSSTYLESHEET)
        self.D4lesson3.setObjectName("D4lesson3")
        self.day4Lessons.addWidget(self.D4lesson3)
        self.D4lesson4 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D4lesson4.sizePolicy().hasHeightForWidth())
        self.D4lesson4.setSizePolicy(sizePolicy)
        self.D4lesson4.setStyleSheet(LESSONSSTYLESHEET)
        self.D4lesson4.setObjectName("D4lesson4")
        self.day4Lessons.addWidget(self.D4lesson4)
        self.D4lesson5 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D4lesson5.sizePolicy().hasHeightForWidth())
        self.D4lesson5.setSizePolicy(sizePolicy)
        self.D4lesson5.setStyleSheet(LESSONSSTYLESHEET)
        self.D4lesson5.setObjectName("D4lesson5")
        self.day4Lessons.addWidget(self.D4lesson5)
        self.D4lesson6 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D4lesson6.sizePolicy().hasHeightForWidth())
        self.D4lesson6.setSizePolicy(sizePolicy)
        self.D4lesson6.setStyleSheet(LESSONSSTYLESHEET)
        self.D4lesson6.setObjectName("D4lesson6")
        self.day4Lessons.addWidget(self.D4lesson6)
        self.daysLine2.addLayout(self.day4Lessons)
        self.day5Lessons = QtWidgets.QVBoxLayout()
        self.day5Lessons.setObjectName("day5Lessons")
        self.D5lesson1 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D5lesson1.sizePolicy().hasHeightForWidth())
        self.D5lesson1.setSizePolicy(sizePolicy)
        self.D5lesson1.setStyleSheet(LESSONSSTYLESHEET)
        self.D5lesson1.setObjectName("D5lesson1")
        self.day5Lessons.addWidget(self.D5lesson1)
        self.D5lesson2 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D5lesson2.sizePolicy().hasHeightForWidth())
        self.D5lesson2.setSizePolicy(sizePolicy)
        self.D5lesson2.setStyleSheet(LESSONSSTYLESHEET)
        self.D5lesson2.setObjectName("D5lesson2")
        self.day5Lessons.addWidget(self.D5lesson2)
        self.D5lesson3 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D5lesson3.sizePolicy().hasHeightForWidth())
        self.D5lesson3.setSizePolicy(sizePolicy)
        self.D5lesson3.setStyleSheet(LESSONSSTYLESHEET)
        self.D5lesson3.setObjectName("D5lesson3")
        self.day5Lessons.addWidget(self.D5lesson3)
        self.D5lesson4 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D5lesson4.sizePolicy().hasHeightForWidth())
        self.D5lesson4.setSizePolicy(sizePolicy)
        self.D5lesson4.setStyleSheet(LESSONSSTYLESHEET)
        self.D5lesson4.setObjectName("D5lesson4")
        self.day5Lessons.addWidget(self.D5lesson4)
        self.D5lesson5 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D5lesson5.sizePolicy().hasHeightForWidth())
        self.D5lesson5.setSizePolicy(sizePolicy)
        self.D5lesson5.setStyleSheet(LESSONSSTYLESHEET)
        self.D5lesson5.setObjectName("D5lesson5")
        self.day5Lessons.addWidget(self.D5lesson5)
        self.D5lesson6 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D5lesson6.sizePolicy().hasHeightForWidth())
        self.D5lesson6.setSizePolicy(sizePolicy)
        self.D5lesson6.setStyleSheet(LESSONSSTYLESHEET)
        self.D5lesson6.setObjectName("D5lesson6")
        self.day5Lessons.addWidget(self.D5lesson6)
        self.daysLine2.addLayout(self.day5Lessons)
        self.day6Lessons = QtWidgets.QVBoxLayout()
        self.day6Lessons.setObjectName("day6Lessons")
        self.D6lesson1 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D6lesson1.sizePolicy().hasHeightForWidth())
        self.D6lesson1.setSizePolicy(sizePolicy)
        self.D6lesson1.setStyleSheet(LESSONSSTYLESHEET)
        self.D6lesson1.setObjectName("D6lesson1")
        self.day6Lessons.addWidget(self.D6lesson1)
        self.D6lesson2 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D6lesson2.sizePolicy().hasHeightForWidth())
        self.D6lesson2.setSizePolicy(sizePolicy)
        self.D6lesson2.setStyleSheet(LESSONSSTYLESHEET)
        self.D6lesson2.setObjectName("D6lesson2")
        self.day6Lessons.addWidget(self.D6lesson2)
        self.D6lesson3 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D6lesson3.sizePolicy().hasHeightForWidth())
        self.D6lesson3.setSizePolicy(sizePolicy)
        self.D6lesson3.setStyleSheet(LESSONSSTYLESHEET)
        self.D6lesson3.setObjectName("D6lesson3")
        self.day6Lessons.addWidget(self.D6lesson3)
        self.D6lesson4 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D6lesson4.sizePolicy().hasHeightForWidth())
        self.D6lesson4.setSizePolicy(sizePolicy)
        self.D6lesson4.setStyleSheet(LESSONSSTYLESHEET)
        self.D6lesson4.setObjectName("D6lesson4")
        self.day6Lessons.addWidget(self.D6lesson4)
        self.D6lesson5 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D6lesson5.sizePolicy().hasHeightForWidth())
        self.D6lesson5.setSizePolicy(sizePolicy)
        self.D6lesson5.setStyleSheet(LESSONSSTYLESHEET)
        self.D6lesson5.setObjectName("D6lesson5")
        self.day6Lessons.addWidget(self.D6lesson5)
        self.D6lesson6 = QtWidgets.QLineEdit(editTimetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D6lesson6.sizePolicy().hasHeightForWidth())
        self.D6lesson6.setSizePolicy(sizePolicy)
        self.D6lesson6.setStyleSheet(LESSONSSTYLESHEET)
        self.D6lesson6.setObjectName("D6lesson6")
        self.day6Lessons.addWidget(self.D6lesson6)
        self.daysLine2.addLayout(self.day6Lessons)
        self.verticalLayout.addLayout(self.daysLine2)
        self.footer = QtWidgets.QHBoxLayout()
        self.footer.setObjectName("footer")
        self.footerInfo = QtWidgets.QLabel(editTimetable)
        self.footerInfo.setStyleSheet("""
            background-color: none;
            color: rgb(255, 255, 255);
            font-size: 12px;
        """)
        self.footerInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.footerInfo.setObjectName("footerInfo")
        self.footer.addWidget(self.footerInfo)
        self.saveButton = QtWidgets.QPushButton(editTimetable)
        self.saveButton.clicked.connect(lambda: self.save())
        self.saveButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("""
            QPushButton {
                background-color: rgb(255, 133, 62);
                border: 0;
                margin: 0;
                border-radius: 5;
                color: white;
            }
            QPushButton:hover {
                background-color:rgb(244, 81, 0);
            }
        """)
        self.saveButton.setObjectName("saveButton")
        self.footer.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.footer)
        self.retranslateUi(editTimetable)
        QtCore.QMetaObject.connectSlotsByName(editTimetable)


    def retranslateUi(self, editTimetable):
        timetableDATA = read(FILE)
        _translate = QtCore.QCoreApplication.translate
        editTimetable.setWindowTitle(_translate("editTimetable", "SCHelper — Редактировать расписание"))
        self.header.setText(_translate("editTimetable", "Редактировать рассписание"))
        for x in range(1, 7):
            for k in range(1, 7):
                getattr(self, f"D{x}lesson{k}").setText(_translate("timetable", timetableDATA[f"D{x}"][f"lesson{k}"]))
        self.day1Line1Name.setText(_translate("editTimetable", "Понедельник"))
        self.day3Line1Name.setText(_translate("editTimetable", "Вторник"))
        self.day2Line1Name.setText(_translate("editTimetable", "Среда"))
        self.day5Line2Name.setText(_translate("editTimetable", "Четверг"))
        self.day6Line2Name.setText(_translate("editTimetable", "Пятница"))
        self.day4Line2Name.setText(_translate("editTimetable", "Суббота"))
        self.footerInfo.setText(_translate("editTimetable", "Нажмите \"Обновить\" после редактирования рассписания"))
        self.saveButton.setText(_translate("editTimetable", "Сохранить"))